### ISSUE TITLE
There are troubles with building pyjnius in current version

### ISSUE THREAD

**Issue by manatlan** [ArtemSBulgakov/buildozer-action#34]
So, it doesn't work anymore AS IS ;-(

is there plan to fix that ? or is there working forks ?

thanks in advance

**Comment by sebastien46** [comment]
Yea I also get this error when trying to build ```pyjnius```:
```
jnius/jnius.c:54433:5: error: expression is not assignable
   	    ++Py_REFCNT(o);
   	    ^ ~~~~~~~~~~~~
jnius/jnius.c:54435:5: error: expression is not assignable
   	    --Py_REFCNT(o);
   	    ^ ~~~~~~~~~~~~
```

**Comment by balasekhar89** [comment]
The following versions fixed the pyjnius issue

Cython==0.29.33,kivy==2.2.0

Add them to requirements in buildozer.spec

**Comment by manatlan** [comment]
Doesn't seem to work for me

**Comment by balasekhar89** [comment]
Updated my previous comment
add change p4a.branch to release-2022.12.20

**Comment by manatlan** [comment]
I've updated my previous thumb !
Your solution works for me too!
Thanks a lot !!!!

**Comment by AHiXilTOr** [comment]
how to build on kivy 2.3.0

**Comment by ArtemSBulgakov** [comment]
The problem was with the new Cython version (3.1.1), however Buildozer requires previous version (0.29.37). This should be fixed in the new release of the action.

Try with buildozer-action [v1.2.0](https://github.com/ArtemSBulgakov/buildozer-action/releases/tag/v1.2.0)
